@authToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzODBlZjEyZjk1ZjkxNmNhZDdhNGNlMzg4ZDJjMmMzYzIzMDJmZGUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTIyODY1OTksInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MjI4NjYwMCwiZXhwIjoxNjkyMjkwMjAwLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.BmPgyKAsRHi2MLez6OeFo9ixOFGZnuyWbSLqe5jmvt93Y-fzbIfhaRDtzXYFqt3AOHHo8NxlDt7Jb3l-uzDPYHufoWQ48RGvrCGZJGXl58_Gr6Ur2LXv7_JXnTHyGLsvwpQbYOQPzCJ9aH8DthtGjo8IobQ2lzG03aUtLQMKJYurU9Z3ZvIAMCzpX45C7ksyOaC4-c_7oRJyOVvW4gGqKwBdtojsrdvW39BylWfwJlMup2U5U6RuJakIk3l3WKF10fJVTh_3_MHKx_PcPmsENmU-MOxH5o5fnzRQGgqcHaNktUi6KhtbFyKcKGwLBqlCgqf8HMJFbmLiJkdN5iJkQw

@baseUrl = http://localhost:3000/api/v1

###
POST {{baseUrl}}/recipes/recipe/
Content-Type: application/json
Authorization: {{authToken}}

{
    "title": "Healthy Oatmeal",
    "description": "Nutritious oatmeal with fruits and nuts",
    "image": "https://example.com/oatmeal.jpg",
    "cook_time": {
      "time_unit": 1,
      "value": 10
    },
    "ingredients": {
      "rolled_oats": {
        "weight_unit": 50,
        "value": 1
      },
      "milk": {
        "weight_unit": 150,
        "value": 1
      },
      "banana": {
        "weight_unit": 100,
        "value": 1
      },
      "berries": {
        "weight_unit": 50,
        "value": 0.5
      },
      "nuts": {
        "weight_unit": 30,
        "value": 0.5
      },
      "honey": {
        "weight_unit": 20,
        "value": 1
      },
      "cinnamon": {
        "weight_unit": 2,
        "value": 1
      }
    }
  }


###
GET {{baseUrl}}/recipes/recipe
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/recipes/recipe?last=1692283390569
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/recipes/recipe/CS8fmriruCO0iw8TzZq0
Content-Type: application/json
Authorization: {{authToken}}

###
POST {{baseUrl}}/recipes/recipe/CS8fmriruCO0iw8TzZq0/rating
Content-Type: application/json
Authorization: {{authToken}}

{
  "rating": 4.5,
  "review": "Absolutely delicious! The flavors blend together perfectly."
}


###
GET {{baseUrl}}/recipes/recipe/CS8fmriruCO0iw8TzZq0/rating
Content-Type: application/json
Authorization: {{authToken}}