@authToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTIxMDA5NzAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MjEwMDk3NywiZXhwIjoxNjkyMTA0NTc3LCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.jc2NOULB8BWP8QahiOdJQbP5ZKSczuJH6mcKeU3rcYeEo9ei1RbSCVYyUfsV1U03YV_dF8P08X4Qxig1OFWM8OY5ojKKojga5rKlF44uFVUif2N4KKw13nt9WmP-ZeN1B405lntizeCEi2cx3qzO5Tv2sMswP6tlCL0vQhfIeQTU45w94jGUwirG4RqV7d-VAyr_LzPU9om6JYdd3ExZqbcmcBfdGEAZR8F6A5T7ludz1t9CF4x761ytb6xQQU6aOi083RPN5GQFmtlYMR76o0Hy31WC_rUh4qMyu60lYJPnw74JRRK6DA20NA-LREt4yxFtIWOUWdG4BcgnwxtHoA


### Fresh token
GET http://localhost:3000/api/v1/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23 
Content-Type: application/json
Authorization: {{authToken}}

### 
GET http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

### 
GET http://localhost:3000/api/v1/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1
Content-Type: application/json
Authorization: {{authToken}}

###
POST http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "first_name": "Deny",
    "last_name": "Hilhamsyah",
    "bio": "Bio example",
    "profile_image": "https://example.com/denyhilhamsyah.jpg"
}

###
PUT http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "bio": "dffBio change"
}

###
POST http://localhost:3000/api/v1/users/user/username
Content-Type: application/json
Authorization: {{authToken}}

{
    "user_name": "denyhilhamsyah"
}