### Fresh token
GET http://localhost:3000/api/v1/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

### 
GET http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

### 
GET http://localhost:3000/api/v1/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

###
POST http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

{
    "first_name": "Deny",
    "last_name": "Hilhamsyah",
    "bio": "Bio example",
    "profile_image": "https://example.com/denyhilhamsyah.jpg"
}

###
PUT http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

{
    "first_name": "Deny",
    "last_name": "Hilhamsyah",
    "bio": "Changed",
    "profile_image": "https://example.com/denyhilhamsyah.jpg"
}

###
POST http://localhost:3000/api/v1/users/user/username
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTE5NDA3MTAsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MTk0MDcxMSwiZXhwIjoxNjkxOTQ0MzExLCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.eE4ZTVhAYuBN75mQ4FoEwLaO770qsZz6UZiodEACCo15MqOVcXwB71NP-a8GWWxSYI-hyTPW9v87zAKDYDhS8IncoKA8hVZ969xYu-kufs94pW1Yk8Iv5AdIqx5y4RUP4Cvj-1Gi789dME2pYZ6i2-g6FJstJBStLBDZ9Uc267M-HEklRXNNybsws2W43eI338oThAKc6q9TG7kZ53DsMVpOmEUvSTzk1ZVCfZczfsWEQka7K_2fWV1Z1QhKcAAtIX5HIITt17Sfa-LgdVvAKRHPjafIVLWPcjWe5JM22LYTUpE4S9_MrXe4TQZ-QxBnqLWBgyBra8_cvnUZQSC9ZA

{
    "user_name": "denyhilhamsyah"
}