@authToken = eyJhbGciOiJSUzI1NiIsImtpZCI6ImNmM2I1YWRhM2NhMzkxNTQ4ZDM1OTJiMzU5MjkyM2UzNjAxMmI5MTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTIxMTE1MDUsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MjExMTUwNiwiZXhwIjoxNjkyMTE1MTA2LCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.ocHYyrvQSBl56sHOt0JZaCEajqOeiV-iaPBjdHtZqRcNBBr3m2-Gfxp3FQgcyzUZ_0Digv15lTNlM27mMdn_FpYAxfl7hjz0kUOBlRijqNbq1WXt8z4SvbFJJVAeahwMbnpUuWNS09EPNGgrRRi8jdScYjNYym4H-pRz1u1eaNFLUscEowWS3wJo1pWsa9kAeytXFgP3IW9DMWeg6NBx4jk8y3MiutfBD4qnBzz-dGqVYa9TI1Kge-lIjv_zPx5igcP8-4afDsvjykhjNOlVnbtxXXRTd3CKclmiqdAdwtG8C5Omx1_KV1lpmrJi9GGzOAz0zvf1H8eG1JAAUjzlUA


### Fresh token
GET http://localhost:3000/api/v1/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23 
Content-Type: application/json
Authorization: {{authToken}}

### 
GET http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

### 
GET http://localhost:3000/api/v1/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1
Content-Type: application/json
Authorization: {{authToken}}

###
POST http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "first_name": "Deny",
    "last_name": "Hilhamsyah",
    "bio": "Bio example",
    "profile_image": "https://example.com/denyhilhamsyah.jpg"
}

###
PUT http://localhost:3000/api/v1/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "bio": "dffBio change"
}

###
POST http://localhost:3000/api/v1/users/user/username
Content-Type: application/json
Authorization: {{authToken}}

{
    "user_name": "denyhilhamsyah"
}

###
POST http://localhost:3000/api/v1/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1/follow
Content-Type: application/json
Authorization: {{authToken}}