@authToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzODBlZjEyZjk1ZjkxNmNhZDdhNGNlMzg4ZDJjMmMzYzIzMDJmZGUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY29va2h1Yi1lMGI0NyIsImF1ZCI6ImNvb2todWItZTBiNDciLCJhdXRoX3RpbWUiOjE2OTIyODgxMjMsInVzZXJfaWQiOiJPUDJzTEN0a01IVW9KTFVrZ0taa2VrUVZvcDIzIiwic3ViIjoiT1Ayc0xDdGtNSFVvSkxVa2dLWmtla1FWb3AyMyIsImlhdCI6MTY5MjI4ODEyNCwiZXhwIjoxNjkyMjkxNzI0LCJlbWFpbCI6ImRlbnloaWxoYW1zeWhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGVueWhpbGhhbXN5aEBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.VzQygpnlOV509TtjQibncQrvs9w7o-cxZIAsQSEQncg8QsWkQwW5ygDiMK4pnNTl67L0IosLPm-FCv8hmSCWPp38iuqhTe_Re_AIPpA4Zle8PHgCi7qa3fIi055Dvr_jRdlequri1GK4Bqf0kwqKXHexfTZ6hlPlX2gAH_OcuEjOfxlrxtQo1Tk6R67wtk9qSeVZ88k_eVhRarj7pO7tSuKh7os9ndkgzmGddxlvjj4gbajSiQOyoQAwj3cpqwSu6flgPOOhx22kuC4WXR-rswYrR-ZMFbf3ZOJZ8qh8YK4lcK9u5fAFe5Ozdq9hHOD6dgWJqxnW_Iio-hvP5qMSrA

@baseUrl = https://cute-red-gopher-boot.cyclic.cloud/api/v1

### Fresh token
GET {{baseUrl}}/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23 
Content-Type: application/json
Authorization: {{authToken}}

### 
GET {{baseUrl}}/users/user
Content-Type: application/json
Authorization: {{authToken}}

### 
GET {{baseUrl}}/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1
Content-Type: application/json
Authorization: {{authToken}}

###
POST {{baseUrl}}/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "first_name": "Deny",
    "last_name": "Hilhamsyah",
    "bio": "Bio example",
    "profile_image": "https://example.com/denyhilhamsyah.jpg"
}

###
PUT {{baseUrl}}/users/user
Content-Type: application/json
Authorization: {{authToken}}

{
    "bio": "dffBio change"
}

###
POST {{baseUrl}}/users/user/username
Content-Type: application/json
Authorization: {{authToken}}

{
    "user_name": "denyhilhamsyah"
}

###
POST {{baseUrl}}/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1/follow
Content-Type: application/json
Authorization: {{authToken}}

###
POST {{baseUrl}}/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1/unfollow
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/users/user/following/fEKWMA4TfsSYXmX9LN8LvshNNzy1
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1/following
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/users/user/fEKWMA4TfsSYXmX9LN8LvshNNzy1/followers?last=2lK3QKUBuP9eRKkUsmtH
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23/recipes
Content-Type: application/json
Authorization: {{authToken}}

###
GET {{baseUrl}}/users/user/OP2sLCtkMHUoJLUkgKZkekQVop23/recipes?last=1692283474168
Content-Type: application/json
Authorization: {{authToken}}